### ISSUE TITLE
Isssue When i Installing Module : Class 'Detection\MobileDetect' not found 

### ISSUE THREAD

**Issue by nakous** [tabbabi/detect_mobile#12]
I get this Message when I am going to install the module, it is block installation do you have any update?
Fatal error: Class 'Detection\MobileDetect' not found in /var/www/vhosts/qui/public_html/modules/detect_mobile/src/Detect/MobileDetect.php on line 11

**Comment by tabbabi** [comment]
run composer install command

**Comment by Natizyskunk** [comment]
Still not working even after runing the comoser install command.
I'm getting exactly the same error:
`Class 'Detection\MobileDetect' not found in /home/super.dev/public_html/dgetn_site/web/modules/custom/detect_mobile/src/Detect/MobileDetect.php on line 11`.
Also this is not how Drupal 8 modules work. 
We should be able to just drop the folder iside our modules folder and then enable it via the drupal extension dashboard.

Any possible fix in the near future ? 🙂

**Comment by angoo** [comment]
This is how I fixed this in a composer-based drupal installation (drupal-composer/drupal-project):

1) in `composer.json` add the _mobiledetectlib_ package to the repositories
`        {
            "type": "package",
            "package": {
                "name": "mobiledetect/mobiledetectlib",
                "version": "2.8.33",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/serbanghita/Mobile-Detect/archive/2.8.33.zip",
                    "type": "zip"
                }
            }
        }`
2) from the command line `composer require mobiledetect/mobiledetectlib`
the library will be downloaded to the path for drupal libraries (by default `web\libraries`)
3) i modified the file `web\modules\contrib\detect_mobile\src\Detect\MobileDetect.php` to load directly the Class from the libraries path, kind of a hack but it works for now.

`require_once dirname(__FILE__) . "../../../../../../libraries/mobiledetectlib/Mobile_Detect.php";`
`namespace Drupal\detect_mobile\Detect;`
`class MobileDetect extends \Mobile_Detect  {}`

4) enable the module `drush en -y detect_mobile`

**Comment by tabbabi** [comment]
@angoo can you create a pull request please ?

**Comment by angoo** [comment]
I think the issue here is that the _vendor_ folder is not autoloaded by Drupal when you `composer install` in the module's folder.
`mobiledetect/mobiledetectlib` needs to be in Drupal's vendor folder in order for the module to work as it is right now.
I proposed a documentation enhancement in a pull request

**Comment by tabbabi** [comment]
readme updated
https://github.com/tabbabi/detect_mobile/pull/16
thanks @angoo
