### ISSUE TITLE
Call to a member function render() on null in /var/www/html/d8rnd/core/lib/Drupal/Core/Template..

### ISSUE THREAD

**Issue by ravindrasingh22** [tabbabi/detect_mobile#2]
After enabling this on drupal 8.1.7 it throws Fatal error: Call to a member function render() on null in /var/www/html/d8rnd/core/lib/Drupal/Core/Template/TwigExtension.php on line 468 error

**Comment by b3wii** [comment]
Drupal 8.1.9:

The website encountered an unexpected error. Please try again later.
Error: Call to a member function render() on null in Drupal\Core\Template\TwigExtension->escapeFilter() (line 468 of core/lib/Drupal/Core/Template/TwigExtension.php).

**Comment by tabbabi** [comment]
I developed this module based on drupal alpha version.
I must do an update but I do not have the time actually.
can we push a pull request ?

**Comment by b3wii** [comment]
![screenshot 109](https://cloud.githubusercontent.com/assets/3820367/18544940/50b2a616-7b37-11e6-90ad-12566f941222.jpg)

**Comment by sd788034** [comment]
patch works fine!

**Comment by tabbabi** [comment]
Thanks @b3wii 
thank you all for the participation

**Comment by tabbabi** [comment]
solved with https://github.com/tabbabi/detect_mobile/pull/4
