### ISSUE TITLE
Doesn't work with 8.3.0

### ISSUE THREAD

**Issue by erik-ruiter** [tabbabi/detect_mobile#5]
Fatal error when using Drupal 8.3.0 related to https://www.drupal.org/node/2869142

**Comment by tabbabi** [comment]
can we push a pull request plz?

**Comment by sd788034** [comment]
same error here, checking https://www.drupal.org/node/2600154

**Comment by kyniema4** [comment]
any solution?

**Comment by andresadanmx** [comment]
I had to use PHP version 5.6 and reinstall to make it work. Apparently with PHP 7 happens the fatal error

**Comment by tabbabi** [comment]
Fixed by @iGore

**Comment by tabbabi** [comment]
ping @erik-ruiter @sd788034 @andresadanmx

**Comment by tabbabi** [comment]
fixed

**Comment by sd788034** [comment]
works fine!
thanks a lot!  @tabbabi
